// src/frontend/src/shared/components/auth/authhero.tsx
import React from 'react';
import { Check, MessageSquare } from 'lucide-react';

type AuthHeroProps = {
  eyebrow: string;
  title: string;
  description: string;
  points: string[];
};

function AuthHero({eyebrow, title, description, points}: AuthHeroProps) {
  return (
    <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-primary to-secondary items-center justify-center p-12 relative overflow-hidden">
      <div className="absolute inset-0 opacity-10" style={{backgroundImage: 'radial-gradient(circle at 20% 80%, white 1px, transparent 1px), radial-gradient(circle at 80% 20%, white 1px, transparent 1px)', backgroundSize: '32px 32px'}} />
      <div className="relative text-center text-primary-content">
        <MessageSquare className="h-24 w-24 mx-auto mb-8 opacity-80" />
        <p className="text-sm font-semibold uppercase tracking-[0.24em] opacity-75 mb-3">{eyebrow}</p>
        <h1 className="text-4xl font-extrabold mb-4">{title}</h1>
        <p className="text-xl opacity-90 mb-8">{description}</p>
        <div className="space-y-4 text-left max-w-xs mx-auto">
          {points.map((point) => (
            <div key={point} className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center">
                <Check className="h-4 w-4" />
              </div>
              <span>{point}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default AuthHero;

// apps/frontend/src/lib/domains/auth/components/AuthHero.svelte
<script lang="ts">
  import { Check, MessageSquare } from "@lucide/svelte";

  let {
    eyebrow,
    title,
    description,
    points,
  }: {
    eyebrow: string;
    title: string;
    description: string;
    points: string[];
  } = $props();
</script>

<div
  class="relative hidden items-center justify-center overflow-hidden bg-linear-to-br from-primary to-secondary p-12 lg:flex lg:w-1/2"
>
  <div
    class="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_20%_80%,white_1px,transparent_1px),radial-gradient(circle_at_80%_20%,white_1px,transparent_1px)] bg-size-[32px_32px]"
    aria-hidden="true"
  ></div>
  <div class="relative text-center text-primary-content">
    <MessageSquare class="mx-auto mb-8 size-24 opacity-80" aria-hidden="true" />
    <p
      class="mb-3 text-sm font-semibold tracking-[0.24em] uppercase opacity-75"
    >
      {eyebrow}
    </p>
    <h1 class="mb-4 text-4xl font-extrabold">{title}</h1>
    <p class="mb-8 text-xl opacity-90">{description}</p>
    <div class="mx-auto max-w-xs space-y-4 text-left">
      {#each points as point (point)}
        <div class="flex items-center gap-3">
          <div
            class="flex size-8 items-center justify-center rounded-full bg-white/20"
          >
            <Check class="size-4" aria-hidden="true" />
          </div>
          <span>{point}</span>
        </div>
      {/each}
    </div>
  </div>
</div>
