// src/frontend/src/shared/components/navbar/navbar.tsx
'use client';

import React, {useState, useEffect, useRef} from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import Avatar from '@/shared/components/avatar/avatar';
import { Sun, Moon, Home, User as UserIcon, Settings, LogOut } from 'lucide-react';
import { useAPI } from '@/shared/contexts/apicontext';
import { useTheme } from '@/shared/hooks/usetheme';

function ThemeToggle() {
  const {resolvedTheme, setTheme} = useTheme();
  const toggle = () => setTheme(resolvedTheme === 'light' ? 'dark' : 'light');

  return (
    <button onClick={toggle} className="btn btn-ghost btn-circle hover:bg-white/40 dark:hover:bg-white/10" aria-label="Toggle theme">
      {resolvedTheme === 'light' ? (
        <Sun className="h-5 w-5" />
      ) : (
        <Moon className="h-5 w-5" />
      )}
    </button>
  );
}
import type { User } from '@/shared/types';

interface NavbarProps {
  isLoggedIn: boolean;
  user?: User | null;
}

function Navbar({isLoggedIn, user}: NavbarProps) {
  const apiClient = useAPI();
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const dropdownRef = useRef(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    function handleClickOutside(e) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
        setIsDropdownOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const toggleDropdown = () => setIsDropdownOpen((v) => !v);
  const closeDropdown = () => setIsDropdownOpen(false);

  const handleLogout = () => {
    apiClient.logout().finally(() => {
      window.location.href = '/login';
    });
  };

  return (
    <nav className="navbar sticky top-0 z-50 min-h-16 border-b border-white/40 bg-white/35 px-3 shadow-none backdrop-blur-2xl backdrop-saturate-150 transition-colors duration-300 dark:border-white/10 dark:bg-slate-950/35 sm:px-4 supports-[backdrop-filter]:bg-white/25 dark:supports-[backdrop-filter]:bg-slate-950/25">
      <div className="navbar-start">
        {isLoggedIn && (
          <Link href="/" className="btn btn-ghost normal-case text-base sm:text-lg gap-2 hover:scale-105 hover:bg-white/40 dark:hover:bg-white/10 transition-transform duration-200">
            <Home className="h-5 w-5 sm:h-6 sm:w-6" />
            <span className="hidden xs:inline sm:inline">Home</span>
          </Link>
        )}
      </div>

      <div className="navbar-center">
        <span className="text-xl sm:text-2xl font-black bg-gradient-to-r from-primary via-fuchsia-500 to-secondary bg-clip-text text-transparent tracking-tight drop-shadow-sm">Thoughts</span>
      </div>

      <div className="navbar-end gap-1">
        <ThemeToggle />
        {isLoggedIn ? (
          <div ref={dropdownRef} className="dropdown dropdown-end">
            <button
              onClick={toggleDropdown}
              className="btn btn-ghost btn-circle avatar hover:bg-white/40 dark:hover:bg-white/10"
              aria-label="User menu"
              aria-expanded={isDropdownOpen}
            >
              <Avatar name={user?.name} size="md" photoKey={user?.profilePhotoKey} />
            </button>
            {isDropdownOpen && (
              <ul className="menu menu-sm dropdown-content z-[1001] mt-3 w-56 rounded-2xl border border-white/70 bg-white/90 p-2 shadow-2xl shadow-slate-900/20 backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/95 dark:shadow-black/50">
                <li className="menu-title px-3 py-1 text-xs opacity-60">Signed in as @{user?.username || 'user'}</li>
                <div className="divider my-1 mx-2 h-px bg-base-200"></div>
                <li onClick={closeDropdown}><Link href={`/@${user?.username}`} className="gap-2 py-2"><UserIcon className="h-4 w-4" />Profile</Link></li>
                <li onClick={closeDropdown}><Link href="/settings" className="gap-2 py-2"><Settings className="h-4 w-4" />Settings</Link></li>
                <div className="divider my-1 mx-2 h-px bg-base-200"></div>
                <li onClick={closeDropdown}>
                  <button onClick={handleLogout} className="text-error gap-2 py-2"><LogOut className="h-4 w-4" />Logout</button>
                </li>
              </ul>
            )}
          </div>
        ) : (
          <Link href="/login" className="btn btn-primary btn-sm rounded-full px-6">Log In</Link>
        )}
      </div>
    </nav>
  );
}

export default Navbar;

// apps/frontend/src/lib/shared/components/layout/Navbar.svelte
<script lang="ts">
  import { resolve } from "$app/paths";
  import { page } from "$app/state";
  import type { User } from "$lib/domains/users/model";
  import { getThemeContext } from "$lib/shared/theme.svelte";
  import Avatar from "$lib/shared/components/ui/Avatar.svelte";
  import {
    Home,
    LogOut,
    Moon,
    Search,
    Settings,
    Sun,
    User as UserIcon,
  } from "@lucide/svelte";
  import { onMount } from "svelte";

  let {
    user = null,
    sessionUnavailable = false,
  }: {
    user?: User | null;
    sessionUnavailable?: boolean;
  } = $props();

  const theme = getThemeContext();
  let menuOpen = $state(false);
  let menu = $state<HTMLDivElement>();

  function toggleTheme(): void {
    theme.set(theme.resolved === "light" ? "dark" : "light");
  }

  onMount(() => {
    const closeOnOutsideClick = (event: MouseEvent) => {
      if (menuOpen && menu && !menu.contains(event.target as Node)) {
        menuOpen = false;
      }
    };
    document.addEventListener("mousedown", closeOnOutsideClick);
    return () => document.removeEventListener("mousedown", closeOnOutsideClick);
  });
</script>

<nav
  class="navbar sticky top-0 z-50 min-h-16 border-b border-white/40 bg-white/35 px-3 shadow-none backdrop-blur-2xl backdrop-saturate-150 transition-colors duration-300 supports-[backdrop-filter]:bg-white/25 dark:border-white/10 dark:bg-slate-950/35 dark:supports-[backdrop-filter]:bg-slate-950/25 sm:px-4"
>
  <div class="navbar-start">
    {#if user || sessionUnavailable}
      <a
        href={resolve("/")}
        class="btn btn-ghost gap-2 text-base normal-case transition-transform duration-200 hover:scale-105 hover:bg-white/40 dark:hover:bg-white/10 sm:text-lg"
        aria-current={page.url.pathname === "/" ? "page" : undefined}
      >
        <Home class="size-5 sm:size-6" aria-hidden="true" />
        <span class="hidden sm:inline">Home</span>
      </a>
      <a
        href={resolve("/search")}
        class="btn btn-ghost gap-2 text-base normal-case transition-transform duration-200 hover:scale-105 hover:bg-white/40 dark:hover:bg-white/10 sm:text-lg"
        aria-current={page.url.pathname === "/search" ? "page" : undefined}
      >
        <Search class="size-5 sm:size-6" aria-hidden="true" />
        <span class="hidden sm:inline">Search</span>
      </a>
    {/if}
  </div>

  <div class="navbar-center">
    <span
      class="bg-gradient-to-r from-primary via-fuchsia-500 to-secondary bg-clip-text text-xl font-black tracking-tight text-transparent drop-shadow-sm sm:text-2xl"
      >Thoughts</span
    >
  </div>

  <div class="navbar-end gap-1">
    <button
      type="button"
      onclick={toggleTheme}
      class="btn btn-ghost btn-circle hover:bg-white/40 dark:hover:bg-white/10"
      aria-label="Toggle theme"
    >
      {#if theme.resolved === "light"}
        <Sun class="size-5" aria-hidden="true" />
      {:else}
        <Moon class="size-5" aria-hidden="true" />
      {/if}
    </button>

    {#if user}
      <div class="dropdown dropdown-end" bind:this={menu}>
        <button
          type="button"
          onclick={() => (menuOpen = !menuOpen)}
          class="btn btn-ghost btn-circle avatar hover:bg-white/40 dark:hover:bg-white/10"
          aria-label="User menu"
          aria-expanded={menuOpen}
        >
          <Avatar name={user.name} photoKey={user.profilePhotoKey} />
        </button>
        {#if menuOpen}
          <ul
            class="menu menu-sm dropdown-content z-[1001] mt-3 w-56 rounded-2xl border border-white/70 bg-white/90 p-2 shadow-2xl shadow-slate-900/20 backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/95 dark:shadow-black/50"
          >
            <li class="menu-title px-3 py-1 text-xs opacity-60">
              Signed in as @{user.username || "user"}
            </li>
            <li><hr class="my-1 border-base-200" /></li>
            <li>
              <a
                href={`/@${user.username}`}
                onclick={() => (menuOpen = false)}
                class="gap-2 py-2"
              >
                <UserIcon class="size-4" aria-hidden="true" />Profile
              </a>
            </li>
            <li>
              <a
                href="/settings"
                onclick={() => (menuOpen = false)}
                class="gap-2 py-2"
              >
                <Settings class="size-4" aria-hidden="true" />Settings
              </a>
            </li>
            <li><hr class="my-1 border-base-200" /></li>
            <li>
              <form method="POST" action="/logout">
                <button type="submit" class="w-full gap-2 py-2 text-error">
                  <LogOut class="size-4" aria-hidden="true" />Logout
                </button>
              </form>
            </li>
          </ul>
        {/if}
      </div>
    {:else if sessionUnavailable}
      <span class="text-xs text-base-content/60">Service unavailable</span>
    {:else}
      <a href="/login" class="btn btn-primary btn-sm rounded-full px-6"
        >Log In</a
      >
    {/if}
  </div>
</nav>
