// apps/frontend/src/app/[username]/_components/useritem.tsx
import {useState} from 'react';
import Link from 'next/link';
import Avatar from '@/shared/components/avatar/avatar';
import { Check, UserPlus } from 'lucide-react';
import GlassCard from '@/shared/components/ui/surface';
import type { User } from '@/shared/types';

interface UserItemProps {
  user: User;
  onFollow?: (userId: string) => Promise<void> | void;
  onUnfollow?: (userId: string) => Promise<void> | void;
  currentUserId?: string | null;
}

function UserItem({user, onFollow, onUnfollow, currentUserId}: UserItemProps) {
  const [isActionLoading, setIsActionLoading] = useState(false);
  const isCurrentUser = currentUserId && user.id === currentUserId;

  function handleFollowClick() {
    if (isActionLoading) return;
    setIsActionLoading(true);
    const action = user.followed ? onUnfollow : onFollow;
    Promise.resolve(action(user.id)).finally(() => setIsActionLoading(false));
  }

  return (
    <GlassCard as="li" interactive className="hover:scale-[1.005]">
      <div className="card-body p-4 sm:p-5">
        <div className="flex items-start justify-between gap-3">
          <Link href={`/@${user.username}`} className="flex items-center gap-3 min-w-0 group">
            <div className="shrink-0 rounded-full p-1 bg-white/45 dark:bg-white/5 ring-1 ring-white/60 dark:ring-white/10 transition-transform duration-200 group-hover:scale-105">
              <Avatar name={user.name} size="md" photoKey={user.profilePhotoKey} />
            </div>
            <div className="min-w-0 pt-0.5">
              <p className="font-semibold truncate text-base-content group-hover:underline">{user.name}</p>
              <p className="text-sm text-slate-500 dark:text-slate-400">@{user.username}</p>
            </div>
          </Link>
          {onFollow && onUnfollow && !isCurrentUser && (
            <button
              type="button"
              className={`btn btn-sm gap-1 rounded-full px-4 shrink-0 shadow-sm transition-all duration-200 hover:scale-105 active:scale-95 ${
                user.followed
                  ? 'btn-outline bg-white/25 dark:bg-white/5 border-white/50 dark:border-white/10'
                  : 'btn-primary shadow-primary/20'
              }`}
              onClick={handleFollowClick}
              disabled={isActionLoading}
            >
              {isActionLoading ? (
                <span className="loading loading-spinner loading-xs" />
              ) : user.followed ? (
                <>
                  <Check className="h-4 w-4" />
                  Following
                </>
              ) : (
                <>
                  <UserPlus className="h-4 w-4" />
                  Follow
                </>
              )}
            </button>
          )}
          {isCurrentUser && (
            <span className="rounded-full px-3 py-1.5 text-xs font-semibold text-slate-500 dark:text-slate-400 bg-white/35 dark:bg-white/5 border border-white/50 dark:border-white/10">
              You
            </span>
          )}
        </div>
        {user.bio && <p className="mt-3 text-sm text-slate-600 dark:text-slate-300 line-clamp-2 leading-relaxed sm:pl-14">{user.bio}</p>}
      </div>
    </GlassCard>
  );
}

export default UserItem;

// apps/frontend/src/lib/domains/users/components/UserItem.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import { resolve } from "$app/paths";
  import Avatar from "$lib/shared/components/ui/Avatar.svelte";
  import { Check, UserPlus } from "@lucide/svelte";
  import GlassCard from "$lib/shared/components/ui/GlassCard.svelte";
  import type { User } from "$lib/shared/types";

  let { user, currentUserId } = $props<{
    user: User;
    currentUserId?: number | null;
  }>();

  let isCurrentUser = $derived(currentUserId && user.id === currentUserId);

  let optimisticFollowOverride = $state<boolean | null>(null);
  let followed = $derived(
    optimisticFollowOverride !== null
      ? optimisticFollowOverride
      : (user.followed ?? false),
  );
  let isActionLoading = $state(false);
</script>

<GlassCard as="li" interactive class="hover:scale-[1.005]">
  <div class="card-body p-4 sm:p-5">
    <div class="flex items-start justify-between gap-3">
      <a
        href={resolve(`/@${user.username}`)}
        class="group flex min-w-0 items-center gap-3"
      >
        <div
          class="shrink-0 rounded-full bg-base-100/55 p-1 ring-1 ring-base-300/80 transition-transform duration-200 group-hover:scale-105 dark:bg-white/5 dark:ring-white/10"
        >
          <Avatar name={user.name} size="md" photoKey={user.profilePhotoKey} />
        </div>
        <div class="min-w-0 pt-0.5">
          <p
            class="truncate font-semibold text-base-content group-hover:underline"
          >
            {user.name}
          </p>
          <p class="muted-text text-sm">
            @{user.username}
          </p>
        </div>
      </a>
      {#if !isCurrentUser}
        <form
          method="POST"
          action="?/toggleFollow"
          use:enhance={() => {
            const wasFollowed = followed;
            optimisticFollowOverride = !wasFollowed;
            isActionLoading = true;

            return async ({ result, update }) => {
              isActionLoading = false;
              optimisticFollowOverride = null;
              if (result.type !== "failure") {
                await update({ invalidateAll: false });
              }
            };
          }}
        >
          <input type="hidden" name="userId" value={user.id} />
          <input
            type="hidden"
            name="action"
            value={followed ? "unfollow" : "follow"}
          />
          <button
            class={`btn btn-sm shrink-0 gap-1 rounded-full px-4 shadow-sm transition-all duration-200 hover:scale-105 active:scale-95 ${
              followed
                ? "btn-outline border-base-300/80 bg-base-100/30 dark:border-white/10 dark:bg-white/5"
                : "btn-primary shadow-primary/20"
            }`}
            disabled={isActionLoading}
          >
            {#if isActionLoading}
              <span class="loading loading-spinner loading-xs"></span>
            {:else if followed}
              <Check class="h-4 w-4" />
              Following
            {:else}
              <UserPlus class="h-4 w-4" />
              Follow
            {/if}
          </button>
        </form>
      {/if}
      {#if isCurrentUser}
        <span
          class="muted-text rounded-full border border-base-300/80 bg-base-100/40 px-3 py-1.5 text-xs font-semibold dark:border-white/10 dark:bg-white/5"
        >
          You
        </span>
      {/if}
    </div>
    {#if user.bio}
      <p
        class="line-clamp-2 mt-3 text-sm leading-relaxed text-base-content/75 sm:pl-14"
      >
        {user.bio}
      </p>
    {/if}
  </div>
</GlassCard>
