// apps/frontend/src/app/login/login.tsx
'use client';

import { useActionState } from 'react';
import Link from 'next/link';
import { AlertCircle, Mail, Lock } from 'lucide-react';
import AuthHero from '@/shared/components/auth/authhero';
import GlassCard, {IconInput} from '@/shared/components/ui/surface';

import { useAPI } from '@/shared/contexts/apicontext';

function Login({error: initialError}: {error?: string | null}) {
  const apiClient = useAPI();

  const [state, formAction, isPending] = useActionState(
    async (prevState: any, formData: FormData) => {
      const email = formData.get('email') as string;
      const password = formData.get('password') as string;
      try {
        await apiClient.login(email, password);
        window.location.href = '/';
        return { error: null };
      } catch (e: any) {
        return { error: e.message || 'Login failed' };
      }
    },
    { error: initialError }
  );

  return (
    <div className="min-h-[calc(100vh-4rem)] flex">
      <AuthHero
        eyebrow="Welcome back"
        title="Thoughts"
        description="Pick up where the conversation left off."
        points={[
          'Share ideas before they fade',
          'Keep up with people you follow',
          'Return to replies, likes, and reposts',
        ]}
      />
      <div className="flex-1 flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-md">

          <GlassCard>
            <div className="card-body">
              <h1 className="card-title text-2xl mb-1">Welcome back</h1>
              <p className="text-base-content/60 mb-6">Log in to keep the conversation moving.</p>

              {state.error && (
                <div className="alert alert-error mb-4">
                  <AlertCircle className="h-5 w-5" />
                  <span>{state.error}</span>
                </div>
              )}

              <form action={formAction} className="space-y-4">
                <div className="form-control">
                  <label className="label"><span className="label-text font-medium">Email</span></label>
                  <IconInput icon={Mail} type="email" name="email" placeholder="you@example.com" required />
                </div>
                <div className="form-control">
                  <label className="label"><span className="label-text font-medium">Password</span></label>
                  <IconInput icon={Lock} type="password" name="password" placeholder="Enter your password" minLength={8} required />
                </div>
                <button type="submit" className="btn btn-primary w-full gap-1 rounded-xl" disabled={isPending}>
                  {isPending ? <span className="loading loading-spinner"></span> : 'Log In'}
                </button>
              </form>

              <div className="divider my-4">or</div>

              <p className="text-center text-sm text-base-content/60">
                Don&apos;t have an account? <Link href="/signup" className="link link-primary font-medium">Sign Up</Link>
              </p>
            </div>
          </GlassCard>
        </div>
      </div>
    </div>
  );
}

export default Login;

// apps/frontend/src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import { resolve } from "$app/paths";
  import AuthHero from "$lib/domains/auth/components/AuthHero.svelte";
  import GlassCard from "$lib/shared/components/ui/GlassCard.svelte";
  import IconInput from "$lib/shared/components/ui/IconInput.svelte";
  import { AlertCircle, Lock, Mail } from "@lucide/svelte";
  import { untrack } from "svelte";
  import type { ActionData } from "./$types";

  let { form }: { form: ActionData } = $props();
  let email = $state(untrack(() => form?.email ?? ""));
  let password = $state("");
  let pending = $state(false);
</script>

<svelte:head>
  <title>Log in · Cogito</title>
</svelte:head>

<div class="flex min-h-[calc(100vh-4rem)]">
  <AuthHero
    eyebrow="Welcome back"
    title="Cogito"
    description="Pick up where the conversation left off."
    points={[
      "Share ideas before they fade",
      "Keep up with people you follow",
      "Return to replies, likes, and reposts",
    ]}
  />

  <div class="flex flex-1 items-center justify-center px-4 py-12">
    <div class="w-full max-w-md">
      <GlassCard>
        <div class="card-body">
          <h1 class="card-title mb-1 text-2xl">Welcome back</h1>
          <p class="mb-6 text-base-content/60">
            Log in to keep the conversation moving.
          </p>

          {#if form?.error}
            <div class="alert alert-error mb-4">
              <AlertCircle class="size-5" aria-hidden="true" />
              <span>{form.error}</span>
            </div>
          {/if}

          <form
            method="POST"
            class="space-y-4"
            use:enhance={() => {
              pending = true;
              return async ({ update }) => {
                pending = false;
                await update();
              };
            }}
          >
            <div class="form-control">
              <label class="label" for="login-email">
                <span class="label-text font-medium">Email</span>
              </label>
              <IconInput
                icon={Mail}
                id="login-email"
                type="email"
                name="email"
                placeholder="you@example.com"
                bind:value={email}
                autocomplete="email"
                required
              />
            </div>
            <div class="form-control">
              <label class="label" for="login-password">
                <span class="label-text font-medium">Password</span>
              </label>
              <IconInput
                icon={Lock}
                id="login-password"
                type="password"
                name="password"
                placeholder="Enter your password"
                bind:value={password}
                autocomplete="current-password"
                minlength={8}
                required
              />
            </div>
            <button
              type="submit"
              class="btn btn-primary w-full gap-1 rounded-xl"
              disabled={pending}
            >
              {#if pending}
                <span class="loading loading-spinner"></span>
              {:else}
                Log In
              {/if}
            </button>
          </form>

          <div class="divider my-4">or</div>
          <p class="text-center text-sm text-base-content/60">
            Don&apos;t have an account?
            <a href={resolve("/signup")} class="link link-primary font-medium"
              >Sign Up</a
            >
          </p>
        </div>
      </GlassCard>
    </div>
  </div>
</div>
